export const cameraStyles = {
  container: { padding: "20px" },
  modeToggle: { display: "flex", justifyContent: "center", gap: "10px", marginBottom: "20px" },
  modeButton: { padding: "12px 24px", fontSize: "14px", fontWeight: "600", backgroundColor: "#f8fafc", border: "2px solid #e2e8f0", borderRadius: "10px", cursor: "pointer", transition: "all 0.2s ease" },
  modeButtonActive: { backgroundColor: "#1e3a5f", borderColor: "#1e3a5f", color: "white" },
  voiceToggle: { textAlign: "center", marginBottom: "20px" },
  voiceLabel: { display: "inline-flex", alignItems: "center", gap: "8px", fontSize: "14px", color: "#64748b", cursor: "pointer" },
  voiceCheckbox: { width: "18px", height: "18px" },
  mainContent: { display: "grid", gridTemplateColumns: "1.5fr 1fr", gap: "30px" },
  videoSection: { display: "flex", flexDirection: "column", gap: "15px" },
  videoContainer: { width: "100%", aspectRatio: "4/3", backgroundColor: "#1a1a2e", borderRadius: "16px", overflow: "hidden", display: "flex", alignItems: "center", justifyContent: "center" },
  video: { width: "100%", height: "100%", objectFit: "cover" },
  videoPlaceholder: { display: "flex", flexDirection: "column", alignItems: "center", gap: "15px", color: "white" },
  placeholderIcon: { fontSize: "64px" },
  startButton: { padding: "12px 24px", fontSize: "14px", fontWeight: "600", backgroundColor: "#1e3a5f", color: "white", border: "none", borderRadius: "8px", cursor: "pointer" },
  controls: { display: "flex", gap: "10px", justifyContent: "center" },
  controlButton: { padding: "12px 24px", fontSize: "14px", fontWeight: "600", backgroundColor: "#f8fafc", border: "2px solid #e2e8f0", borderRadius: "10px", cursor: "pointer" },
  detectButton: { padding: "12px 24px", fontSize: "14px", fontWeight: "600", backgroundColor: "#1e3a5f", color: "white", border: "none", borderRadius: "10px", cursor: "pointer" },
  uploadContainer: { width: "100%", aspectRatio: "4/3" },
  uploadArea: { width: "100%", height: "100%", backgroundColor: "#f8fafc", border: "3px dashed #e2e8f0", borderRadius: "16px", display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center", cursor: "pointer", transition: "all 0.2s ease" },
  fileInput: { display: "none" },
  uploadIcon: { fontSize: "64px", marginBottom: "15px" },
  uploadHint: { fontSize: "12px", color: "#94a3b8", marginTop: "5px" },
  imagePreview: { position: "relative", width: "100%", height: "100%" },
  uploadedImage: { width: "100%", height: "100%", objectFit: "contain", borderRadius: "16px" },
  clearButton: { position: "absolute", top: "10px", right: "10px", width: "30px", height: "30px", backgroundColor: "#dc2626", color: "white", border: "none", borderRadius: "50%", cursor: "pointer", fontSize: "14px" },
  resultsSection: { backgroundColor: "#f8fafc", borderRadius: "16px", padding: "20px" },
  resultsTitle: { fontSize: "18px", fontWeight: "600", color: "#1e293b", marginBottom: "20px" },
  resultCard: { textAlign: "center" },
  signDisplay: { marginBottom: "20px" },
  signEmoji: { fontSize: "64px", display: "block", marginBottom: "10px" },
  signLetter: { fontSize: "48px", fontWeight: "700", color: "#1e3a5f" },
  confidenceBar: { display: "flex", alignItems: "center", gap: "10px", marginBottom: "20px" },
  confidenceLabel: { fontSize: "14px", color: "#64748b" },
  confidenceTrack: { flex: "1", height: "8px", backgroundColor: "#e2e8f0", borderRadius: "4px", overflow: "hidden" },
  confidenceFill: { height: "100%", backgroundColor: "#059669", borderRadius: "4px" },
  confidenceValue: { fontSize: "14px", fontWeight: "600", color: "#059669", minWidth: "45px" },
  speakButton: { width: "100%", padding: "12px", fontSize: "14px", fontWeight: "600", backgroundColor: "#1e3a5f", color: "white", border: "none", borderRadius: "10px", cursor: "pointer", marginBottom: "10px" },
  clearResultsButton: { padding: "8px 16px", fontSize: "12px", backgroundColor: "transparent", color: "#64748b", border: "1px solid #e2e8f0", borderRadius: "6px", cursor: "pointer" },
  noResult: { textAlign: "center", padding: "40px 20px", color: "#64748b" },
  noResultIcon: { fontSize: "48px", display: "block", marginBottom: "15px" },
  noResultHint: { fontSize: "12px", color: "#94a3b8" },
  historySection: { marginTop: "20px", paddingTop: "20px", borderTop: "1px solid #e2e8f0" },
  historyTitle: { fontSize: "14px", fontWeight: "600", color: "#1e293b", marginBottom: "12px" },
  historyItem: { display: "flex", justifyContent: "space-between", alignItems: "center", padding: "10px", backgroundColor: "white", borderRadius: "8px", marginBottom: "8px" },
  historySign: { fontSize: "14px", fontWeight: "600", color: "#1e3a5f" },
  historyConfidence: { fontSize: "12px", color: "#059669" },
  loadingSpinner: {
    border: '4px solid #f3f3f3',
    borderTop: '4px solid #1e3a5f',
    borderRadius: '50%',
    width: '40px',
    height: '40px',
    animation: 'spin 1s linear infinite',
    margin: '20px auto'
  },
  errorMessage: {
    color: '#dc2626',
    backgroundColor: '#fef2f2',
    padding: '15px',
    borderRadius: '8px',
    borderLeft: '4px solid #dc2626',
    margin: '10px 0'
  },
  retryButton: {
    padding: '8px 16px',
    backgroundColor: '#1e3a5f',
    color: 'white',
    border: 'none',
    borderRadius: '6px',
    cursor: 'pointer',
    marginTop: '10px'
  }
};

